=== kpatel7262/assign2-KrishnaPatel-xml-ticket-application/assignment2-KrishnaPatel-XML/xml/ticket_details.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="tickets">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ticket" maxOccurs="unbounded" minOccurs="1">
					<xs:complexType>
						
						<xs:sequence>
							
							<!--ticket status-->
							<xs:element name="ticket_status" type="ticket_status" />
							<!--ticket complaint-->
							<xs:element name="complaint" type="xs:string" />
							<!--ticket reply-->
							<xs:element name="reply" type="xs:string" />
						</xs:sequence>
						
						<xs:attribute name="id" type="xs:string" use="required" />
						<xs:attribute name="user_id" type="xs:string" use="required" />
						<xs:attribute name="dt" type="xs:dateTime" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


<!--options for ticket status-->
  	<xs:simpleType name="ticket_status">
	    <xs:restriction base="xs:string">
	      <xs:enumeration value="on-going" />
	      <xs:enumeration value="resolved" />
	    </xs:restriction>
  	</xs:simpleType>


</xs:schema>

=== kpatel7262/assign2-KrishnaPatel-xml-ticket-application/assignment2-KrishnaPatel-XML/xml/ticket_details.xml
<?xml version="1.0" encoding="utf-8"?>
<tickets xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ticket_details.xsd">
	<!--ticket 1-->
	<ticket id="1" user_id="mg" dt="2020-02-16T05:50:06">
		<!--status of ticket ongoing or solved-->
		<ticket_status>on-going</ticket_status>
		<complaint>product not working well</complaint>
		<reply>Will look into it</reply>
	</ticket>
	<ticket id="2" user_id="mg" dt="2020-03-25T11:10:25">
		<!--status of ticket ongoing or solved-->
		<ticket_status>solved</ticket_status>
		<complaint>product starts working well</complaint>
		<reply>Solved</reply>
	</ticket>
	<ticket id="3" user_id="k" dt="2010-03-25T14:10:25">
		<!--status of ticket ongoing or solved-->
		<ticket_status>ongoing</ticket_status>
		<complaint>check this complaint</complaint>
		<reply>working on it!</reply>
	</ticket>
</tickets>
